# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('bitbucket')


class _ExportableConfig(types.ModuleType):
    @property
    def oauth_client_id(self) -> Optional[str]:
        return __config__.get('oauthClientId') or _utilities.get_env('BITBUCKET_OAUTH_CLIENT_ID')

    @property
    def oauth_client_secret(self) -> Optional[str]:
        return __config__.get('oauthClientSecret') or _utilities.get_env('BITBUCKET_OAUTH_CLIENT_SECRET')

    @property
    def oauth_token(self) -> Optional[str]:
        return __config__.get('oauthToken') or _utilities.get_env('BITBUCKET_OAUTH_TOKEN')

    @property
    def password(self) -> Optional[str]:
        return __config__.get('password') or _utilities.get_env('BITBUCKET_PASSWORD')

    @property
    def username(self) -> Optional[str]:
        return __config__.get('username') or _utilities.get_env('BITBUCKET_USERNAME')

