// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bitbucket

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-bitbucket/sdk/go/bitbucket/internal"
)

// Provides a way to fetch data on a Deployment.
//
// OAuth2 Scopes: `none`
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-bitbucket/sdk/go/bitbucket"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := bitbucket.LookupDeployment(ctx, &bitbucket.LookupDeploymentArgs{
//				Repository: "example",
//				Uuid:       "example",
//				Workspace:  "example",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupDeployment(ctx *pulumi.Context, args *LookupDeploymentArgs, opts ...pulumi.InvokeOption) (*LookupDeploymentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDeploymentResult
	err := ctx.Invoke("bitbucket:index/getDeployment:getDeployment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDeployment.
type LookupDeploymentArgs struct {
	// The repository name.
	Repository string `pulumi:"repository"`
	// The environment UUID.
	Uuid string `pulumi:"uuid"`
	// The workspace name.
	Workspace string `pulumi:"workspace"`
}

// A collection of values returned by getDeployment.
type LookupDeploymentResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The name of the environment.
	Name       string `pulumi:"name"`
	Repository string `pulumi:"repository"`
	// The stage (Test, Staging, Production).
	Stage     string `pulumi:"stage"`
	Uuid      string `pulumi:"uuid"`
	Workspace string `pulumi:"workspace"`
}

func LookupDeploymentOutput(ctx *pulumi.Context, args LookupDeploymentOutputArgs, opts ...pulumi.InvokeOption) LookupDeploymentResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDeploymentResult, error) {
			args := v.(LookupDeploymentArgs)
			r, err := LookupDeployment(ctx, &args, opts...)
			var s LookupDeploymentResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDeploymentResultOutput)
}

// A collection of arguments for invoking getDeployment.
type LookupDeploymentOutputArgs struct {
	// The repository name.
	Repository pulumi.StringInput `pulumi:"repository"`
	// The environment UUID.
	Uuid pulumi.StringInput `pulumi:"uuid"`
	// The workspace name.
	Workspace pulumi.StringInput `pulumi:"workspace"`
}

func (LookupDeploymentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDeploymentArgs)(nil)).Elem()
}

// A collection of values returned by getDeployment.
type LookupDeploymentResultOutput struct{ *pulumi.OutputState }

func (LookupDeploymentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDeploymentResult)(nil)).Elem()
}

func (o LookupDeploymentResultOutput) ToLookupDeploymentResultOutput() LookupDeploymentResultOutput {
	return o
}

func (o LookupDeploymentResultOutput) ToLookupDeploymentResultOutputWithContext(ctx context.Context) LookupDeploymentResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDeploymentResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeploymentResult) string { return v.Id }).(pulumi.StringOutput)
}

// The name of the environment.
func (o LookupDeploymentResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeploymentResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDeploymentResultOutput) Repository() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeploymentResult) string { return v.Repository }).(pulumi.StringOutput)
}

// The stage (Test, Staging, Production).
func (o LookupDeploymentResultOutput) Stage() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeploymentResult) string { return v.Stage }).(pulumi.StringOutput)
}

func (o LookupDeploymentResultOutput) Uuid() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeploymentResult) string { return v.Uuid }).(pulumi.StringOutput)
}

func (o LookupDeploymentResultOutput) Workspace() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeploymentResult) string { return v.Workspace }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDeploymentResultOutput{})
}
