// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bitbucket

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/ryan-pip/pulumi-bitbucket/sdk/go/bitbucket/internal"
)

// Provides a way to fetch data on a pipeline OIDC Config Keys.
//
// OAuth2 Scopes: `none`
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/ryan-pip/pulumi-bitbucket/sdk/go/bitbucket"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := bitbucket.GetPipelineOidcConfigKeys(ctx, &bitbucket.GetPipelineOidcConfigKeysArgs{
//				Workspace: "example",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetPipelineOidcConfigKeys(ctx *pulumi.Context, args *GetPipelineOidcConfigKeysArgs, opts ...pulumi.InvokeOption) (*GetPipelineOidcConfigKeysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPipelineOidcConfigKeysResult
	err := ctx.Invoke("bitbucket:index/getPipelineOidcConfigKeys:getPipelineOidcConfigKeys", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPipelineOidcConfigKeys.
type GetPipelineOidcConfigKeysArgs struct {
	// The workspace to fetch pipeline oidc config keys.
	Workspace string `pulumi:"workspace"`
}

// A collection of values returned by getPipelineOidcConfigKeys.
type GetPipelineOidcConfigKeysResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	Keys      string `pulumi:"keys"`
	Workspace string `pulumi:"workspace"`
}

func GetPipelineOidcConfigKeysOutput(ctx *pulumi.Context, args GetPipelineOidcConfigKeysOutputArgs, opts ...pulumi.InvokeOption) GetPipelineOidcConfigKeysResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetPipelineOidcConfigKeysResult, error) {
			args := v.(GetPipelineOidcConfigKeysArgs)
			r, err := GetPipelineOidcConfigKeys(ctx, &args, opts...)
			var s GetPipelineOidcConfigKeysResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetPipelineOidcConfigKeysResultOutput)
}

// A collection of arguments for invoking getPipelineOidcConfigKeys.
type GetPipelineOidcConfigKeysOutputArgs struct {
	// The workspace to fetch pipeline oidc config keys.
	Workspace pulumi.StringInput `pulumi:"workspace"`
}

func (GetPipelineOidcConfigKeysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPipelineOidcConfigKeysArgs)(nil)).Elem()
}

// A collection of values returned by getPipelineOidcConfigKeys.
type GetPipelineOidcConfigKeysResultOutput struct{ *pulumi.OutputState }

func (GetPipelineOidcConfigKeysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPipelineOidcConfigKeysResult)(nil)).Elem()
}

func (o GetPipelineOidcConfigKeysResultOutput) ToGetPipelineOidcConfigKeysResultOutput() GetPipelineOidcConfigKeysResultOutput {
	return o
}

func (o GetPipelineOidcConfigKeysResultOutput) ToGetPipelineOidcConfigKeysResultOutputWithContext(ctx context.Context) GetPipelineOidcConfigKeysResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetPipelineOidcConfigKeysResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPipelineOidcConfigKeysResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPipelineOidcConfigKeysResultOutput) Keys() pulumi.StringOutput {
	return o.ApplyT(func(v GetPipelineOidcConfigKeysResult) string { return v.Keys }).(pulumi.StringOutput)
}

func (o GetPipelineOidcConfigKeysResultOutput) Workspace() pulumi.StringOutput {
	return o.ApplyT(func(v GetPipelineOidcConfigKeysResult) string { return v.Workspace }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPipelineOidcConfigKeysResultOutput{})
}
