// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bitbucket
{
    /// <summary>
    /// This resource allows you to setup pipelines variables to manage your builds with. Once you have enabled pipelines on your repository you can then further setup variables here to use.
    /// 
    /// OAuth2 Scopes: `none`
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Bitbucket = Pulumi.Bitbucket;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var monorepo = new Bitbucket.Repository("monorepo", new()
    ///     {
    ///         Owner = "gob",
    ///         PipelinesEnabled = true,
    ///     });
    /// 
    ///     var debug = new Bitbucket.RepositoryVariable("debug", new()
    ///     {
    ///         Key = "DEBUG",
    ///         Value = "true",
    ///         Repository = monorepo.Id,
    ///         Secured = false,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Repository Variables can be imported using their `workspace/repository/key/uuid` ID, e.g.
    /// 
    /// ```sh
    ///  $ pulumi import bitbucket:index/repositoryVariable:RepositoryVariable example workspace/repository/key/uuid
    /// ```
    /// </summary>
    [BitbucketResourceType("bitbucket:index/repositoryVariable:RepositoryVariable")]
    public partial class RepositoryVariable : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The key of the key value pair
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// The repository ID you want to put this variable onto. (of form workspace-id/repository-id)
        /// </summary>
        [Output("repository")]
        public Output<string> Repository { get; private set; } = null!;

        /// <summary>
        /// If you want to make this viewable in the UI.
        /// </summary>
        [Output("secured")]
        public Output<bool?> Secured { get; private set; } = null!;

        /// <summary>
        /// (Computed) The UUID identifying the variable.
        /// </summary>
        [Output("uuid")]
        public Output<string> Uuid { get; private set; } = null!;

        /// <summary>
        /// The value of the key. This will not be returned if `secured` is set to true from API and wont be drift detected by provider.
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;

        /// <summary>
        /// (Computed) The workspace the variable is created in.
        /// </summary>
        [Output("workspace")]
        public Output<string> Workspace { get; private set; } = null!;


        /// <summary>
        /// Create a RepositoryVariable resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RepositoryVariable(string name, RepositoryVariableArgs args, CustomResourceOptions? options = null)
            : base("bitbucket:index/repositoryVariable:RepositoryVariable", name, args ?? new RepositoryVariableArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RepositoryVariable(string name, Input<string> id, RepositoryVariableState? state = null, CustomResourceOptions? options = null)
            : base("bitbucket:index/repositoryVariable:RepositoryVariable", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ryan-pip",
                AdditionalSecretOutputs =
                {
                    "value",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RepositoryVariable resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RepositoryVariable Get(string name, Input<string> id, RepositoryVariableState? state = null, CustomResourceOptions? options = null)
        {
            return new RepositoryVariable(name, id, state, options);
        }
    }

    public sealed class RepositoryVariableArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key of the key value pair
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The repository ID you want to put this variable onto. (of form workspace-id/repository-id)
        /// </summary>
        [Input("repository", required: true)]
        public Input<string> Repository { get; set; } = null!;

        /// <summary>
        /// If you want to make this viewable in the UI.
        /// </summary>
        [Input("secured")]
        public Input<bool>? Secured { get; set; }

        [Input("value", required: true)]
        private Input<string>? _value;

        /// <summary>
        /// The value of the key. This will not be returned if `secured` is set to true from API and wont be drift detected by provider.
        /// </summary>
        public Input<string>? Value
        {
            get => _value;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _value = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public RepositoryVariableArgs()
        {
        }
        public static new RepositoryVariableArgs Empty => new RepositoryVariableArgs();
    }

    public sealed class RepositoryVariableState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The key of the key value pair
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The repository ID you want to put this variable onto. (of form workspace-id/repository-id)
        /// </summary>
        [Input("repository")]
        public Input<string>? Repository { get; set; }

        /// <summary>
        /// If you want to make this viewable in the UI.
        /// </summary>
        [Input("secured")]
        public Input<bool>? Secured { get; set; }

        /// <summary>
        /// (Computed) The UUID identifying the variable.
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        [Input("value")]
        private Input<string>? _value;

        /// <summary>
        /// The value of the key. This will not be returned if `secured` is set to true from API and wont be drift detected by provider.
        /// </summary>
        public Input<string>? Value
        {
            get => _value;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _value = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// (Computed) The workspace the variable is created in.
        /// </summary>
        [Input("workspace")]
        public Input<string>? Workspace { get; set; }

        public RepositoryVariableState()
        {
        }
        public static new RepositoryVariableState Empty => new RepositoryVariableState();
    }
}
