// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/ryan-pip/pulumi-bitbucket/sdk/go/bitbucket/internal"
)

var _ = internal.GetEnvOrDefault

func GetOauthClientId(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "bitbucket:oauthClientId")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BITBUCKET_OAUTH_CLIENT_ID"); d != nil {
		value = d.(string)
	}
	return value
}
func GetOauthClientSecret(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "bitbucket:oauthClientSecret")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BITBUCKET_OAUTH_CLIENT_SECRET"); d != nil {
		value = d.(string)
	}
	return value
}
func GetOauthToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "bitbucket:oauthToken")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BITBUCKET_OAUTH_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
func GetPassword(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "bitbucket:password")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BITBUCKET_PASSWORD"); d != nil {
		value = d.(string)
	}
	return value
}
func GetUsername(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "bitbucket:username")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "BITBUCKET_USERNAME"); d != nil {
		value = d.(string)
	}
	return value
}
