// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bitbucket.Outputs
{

    [OutputType]
    public sealed class GetCurrentUserEmailResult
    {
        /// <summary>
        /// The email address.
        /// </summary>
        public readonly string Email;
        /// <summary>
        /// Whether the email is confirmed.
        /// </summary>
        public readonly bool IsConfirmed;
        /// <summary>
        /// Whether is primary email for the user.
        /// </summary>
        public readonly bool IsPrimary;

        [OutputConstructor]
        private GetCurrentUserEmailResult(
            string email,

            bool isConfirmed,

            bool isPrimary)
        {
            Email = email;
            IsConfirmed = isConfirmed;
            IsPrimary = isPrimary;
        }
    }
}
