// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bitbucket.Outputs
{

    [OutputType]
    public sealed class GetHookTypesHookTypeResult
    {
        /// <summary>
        /// The category this event belongs to.
        /// </summary>
        public readonly string Category;
        /// <summary>
        /// More detailed description of the webhook event type.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The event identifier.
        /// </summary>
        public readonly string Event;
        /// <summary>
        /// Summary of the webhook event type.
        /// </summary>
        public readonly string Label;

        [OutputConstructor]
        private GetHookTypesHookTypeResult(
            string category,

            string description,

            string @event,

            string label)
        {
            Category = category;
            Description = description;
            Event = @event;
            Label = label;
        }
    }
}
