// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bitbucket.Outputs
{

    [OutputType]
    public sealed class ProjectBranchingModelProduction
    {
        /// <summary>
        /// Optional and only returned for a project's branching model. Indicates if the indicated branch exists on the project (`false`) or not (`true`). This is useful for determining a fallback to the mainbranch when a project is inheriting its project's branching model.
        /// </summary>
        public readonly bool? BranchDoesNotExist;
        /// <summary>
        /// Indicates if branch is enabled or not.
        /// </summary>
        public readonly bool? Enabled;
        public readonly bool? IsValid;
        /// <summary>
        /// The configured branch. It must be null when `use_mainbranch` is true. Otherwise it must be a non-empty value. It is possible for the configured branch to not exist (e.g. it was deleted after the settings are set).
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// Indicates if the setting points at an explicit branch (`false`) or tracks the main branch (`true`). When `true` the name must be null or not provided. When `false` the name must contain a non-empty branch name.
        /// </summary>
        public readonly bool? UseMainbranch;

        [OutputConstructor]
        private ProjectBranchingModelProduction(
            bool? branchDoesNotExist,

            bool? enabled,

            bool? isValid,

            string? name,

            bool? useMainbranch)
        {
            BranchDoesNotExist = branchDoesNotExist;
            Enabled = enabled;
            IsValid = isValid;
            Name = name;
            UseMainbranch = useMainbranch;
        }
    }
}
