# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .branch_restriction import *
from .branching_model import *
from .commit_file import *
from .default_reviewers import *
from .deploy_key import *
from .deployment import *
from .deployment_variable import *
from .forked_repository import *
from .get_current_user import *
from .get_deployment import *
from .get_group import *
from .get_group_members import *
from .get_groups import *
from .get_hook_types import *
from .get_ip_ranges import *
from .get_pipeline_oidc_config import *
from .get_pipeline_oidc_config_keys import *
from .get_user import *
from .get_workspace import *
from .get_workspace_members import *
from .group import *
from .group_membership import *
from .hook import *
from .pipeline_schedule import *
from .pipeline_ssh_key import *
from .pipeline_ssh_known_host import *
from .project import *
from .project_branching_model import *
from .project_default_reviewers import *
from .provider import *
from .repository import *
from .repository_group_permission import *
from .repository_user_permission import *
from .repository_variable import *
from .ssh_key import *
from .workspace_hook import *
from .workspace_variable import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_bitbucket.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_bitbucket.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "bitbucket",
  "mod": "index/branchRestriction",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/branchRestriction:BranchRestriction": "BranchRestriction"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/branchingModel",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/branchingModel:BranchingModel": "BranchingModel"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/commitFile",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/commitFile:CommitFile": "CommitFile"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/defaultReviewers",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/defaultReviewers:DefaultReviewers": "DefaultReviewers"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/deployKey",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/deployKey:DeployKey": "DeployKey"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/deployment",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/deployment:Deployment": "Deployment"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/deploymentVariable",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/deploymentVariable:DeploymentVariable": "DeploymentVariable"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/forkedRepository",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/forkedRepository:ForkedRepository": "ForkedRepository"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/group",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/group:Group": "Group"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/groupMembership",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/groupMembership:GroupMembership": "GroupMembership"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/hook",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/hook:Hook": "Hook"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/pipelineSchedule",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/pipelineSchedule:PipelineSchedule": "PipelineSchedule"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/pipelineSshKey",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/pipelineSshKey:PipelineSshKey": "PipelineSshKey"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/pipelineSshKnownHost",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/pipelineSshKnownHost:PipelineSshKnownHost": "PipelineSshKnownHost"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/project",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/project:Project": "Project"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/projectBranchingModel",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/projectBranchingModel:ProjectBranchingModel": "ProjectBranchingModel"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/projectDefaultReviewers",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/projectDefaultReviewers:ProjectDefaultReviewers": "ProjectDefaultReviewers"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/repository",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/repository:Repository": "Repository"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/repositoryGroupPermission",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/repositoryGroupPermission:RepositoryGroupPermission": "RepositoryGroupPermission"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/repositoryUserPermission",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/repositoryUserPermission:RepositoryUserPermission": "RepositoryUserPermission"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/repositoryVariable",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/repositoryVariable:RepositoryVariable": "RepositoryVariable"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/sshKey",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/sshKey:SshKey": "SshKey"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/workspaceHook",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/workspaceHook:WorkspaceHook": "WorkspaceHook"
  }
 },
 {
  "pkg": "bitbucket",
  "mod": "index/workspaceVariable",
  "fqn": "pulumi_bitbucket",
  "classes": {
   "bitbucket:index/workspaceVariable:WorkspaceVariable": "WorkspaceVariable"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "bitbucket",
  "token": "pulumi:providers:bitbucket",
  "fqn": "pulumi_bitbucket",
  "class": "Provider"
 }
]
"""
)
