// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class BranchRestriction extends pulumi.CustomResource {
    /**
     * Get an existing BranchRestriction resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: BranchRestrictionState, opts?: pulumi.CustomResourceOptions): BranchRestriction {
        return new BranchRestriction(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bitbucket:index/branchRestriction:BranchRestriction';

    /**
     * Returns true if the given object is an instance of BranchRestriction.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is BranchRestriction {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === BranchRestriction.__pulumiType;
    }

    public readonly branchMatchKind!: pulumi.Output<string | undefined>;
    public readonly branchType!: pulumi.Output<string | undefined>;
    public readonly groups!: pulumi.Output<outputs.BranchRestrictionGroup[] | undefined>;
    public readonly kind!: pulumi.Output<string>;
    public readonly owner!: pulumi.Output<string>;
    public readonly pattern!: pulumi.Output<string | undefined>;
    public readonly repository!: pulumi.Output<string>;
    public readonly users!: pulumi.Output<string[] | undefined>;
    public readonly value!: pulumi.Output<number | undefined>;

    /**
     * Create a BranchRestriction resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: BranchRestrictionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: BranchRestrictionArgs | BranchRestrictionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as BranchRestrictionState | undefined;
            resourceInputs["branchMatchKind"] = state ? state.branchMatchKind : undefined;
            resourceInputs["branchType"] = state ? state.branchType : undefined;
            resourceInputs["groups"] = state ? state.groups : undefined;
            resourceInputs["kind"] = state ? state.kind : undefined;
            resourceInputs["owner"] = state ? state.owner : undefined;
            resourceInputs["pattern"] = state ? state.pattern : undefined;
            resourceInputs["repository"] = state ? state.repository : undefined;
            resourceInputs["users"] = state ? state.users : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
        } else {
            const args = argsOrState as BranchRestrictionArgs | undefined;
            if ((!args || args.kind === undefined) && !opts.urn) {
                throw new Error("Missing required property 'kind'");
            }
            if ((!args || args.owner === undefined) && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if ((!args || args.repository === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            resourceInputs["branchMatchKind"] = args ? args.branchMatchKind : undefined;
            resourceInputs["branchType"] = args ? args.branchType : undefined;
            resourceInputs["groups"] = args ? args.groups : undefined;
            resourceInputs["kind"] = args ? args.kind : undefined;
            resourceInputs["owner"] = args ? args.owner : undefined;
            resourceInputs["pattern"] = args ? args.pattern : undefined;
            resourceInputs["repository"] = args ? args.repository : undefined;
            resourceInputs["users"] = args ? args.users : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(BranchRestriction.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering BranchRestriction resources.
 */
export interface BranchRestrictionState {
    branchMatchKind?: pulumi.Input<string>;
    branchType?: pulumi.Input<string>;
    groups?: pulumi.Input<pulumi.Input<inputs.BranchRestrictionGroup>[]>;
    kind?: pulumi.Input<string>;
    owner?: pulumi.Input<string>;
    pattern?: pulumi.Input<string>;
    repository?: pulumi.Input<string>;
    users?: pulumi.Input<pulumi.Input<string>[]>;
    value?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a BranchRestriction resource.
 */
export interface BranchRestrictionArgs {
    branchMatchKind?: pulumi.Input<string>;
    branchType?: pulumi.Input<string>;
    groups?: pulumi.Input<pulumi.Input<inputs.BranchRestrictionGroup>[]>;
    kind: pulumi.Input<string>;
    owner: pulumi.Input<string>;
    pattern?: pulumi.Input<string>;
    repository: pulumi.Input<string>;
    users?: pulumi.Input<pulumi.Input<string>[]>;
    value?: pulumi.Input<number>;
}
