// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DefaultReviewers extends pulumi.CustomResource {
    /**
     * Get an existing DefaultReviewers resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DefaultReviewersState, opts?: pulumi.CustomResourceOptions): DefaultReviewers {
        return new DefaultReviewers(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bitbucket:index/defaultReviewers:DefaultReviewers';

    /**
     * Returns true if the given object is an instance of DefaultReviewers.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DefaultReviewers {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DefaultReviewers.__pulumiType;
    }

    public readonly owner!: pulumi.Output<string>;
    public readonly repository!: pulumi.Output<string>;
    public readonly reviewers!: pulumi.Output<string[]>;

    /**
     * Create a DefaultReviewers resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DefaultReviewersArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DefaultReviewersArgs | DefaultReviewersState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DefaultReviewersState | undefined;
            resourceInputs["owner"] = state ? state.owner : undefined;
            resourceInputs["repository"] = state ? state.repository : undefined;
            resourceInputs["reviewers"] = state ? state.reviewers : undefined;
        } else {
            const args = argsOrState as DefaultReviewersArgs | undefined;
            if ((!args || args.owner === undefined) && !opts.urn) {
                throw new Error("Missing required property 'owner'");
            }
            if ((!args || args.repository === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            if ((!args || args.reviewers === undefined) && !opts.urn) {
                throw new Error("Missing required property 'reviewers'");
            }
            resourceInputs["owner"] = args ? args.owner : undefined;
            resourceInputs["repository"] = args ? args.repository : undefined;
            resourceInputs["reviewers"] = args ? args.reviewers : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DefaultReviewers.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DefaultReviewers resources.
 */
export interface DefaultReviewersState {
    owner?: pulumi.Input<string>;
    repository?: pulumi.Input<string>;
    reviewers?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a DefaultReviewers resource.
 */
export interface DefaultReviewersArgs {
    owner: pulumi.Input<string>;
    repository: pulumi.Input<string>;
    reviewers: pulumi.Input<pulumi.Input<string>[]>;
}
