// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getHookTypes(args: GetHookTypesArgs, opts?: pulumi.InvokeOptions): Promise<GetHookTypesResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bitbucket:index/getHookTypes:getHookTypes", {
        "subjectType": args.subjectType,
    }, opts);
}

/**
 * A collection of arguments for invoking getHookTypes.
 */
export interface GetHookTypesArgs {
    subjectType: string;
}

/**
 * A collection of values returned by getHookTypes.
 */
export interface GetHookTypesResult {
    readonly hookTypes: outputs.GetHookTypesHookType[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly subjectType: string;
}
export function getHookTypesOutput(args: GetHookTypesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHookTypesResult> {
    return pulumi.output(args).apply((a: any) => getHookTypes(a, opts))
}

/**
 * A collection of arguments for invoking getHookTypes.
 */
export interface GetHookTypesOutputArgs {
    subjectType: pulumi.Input<string>;
}
