// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPipelineOidcConfig(args: GetPipelineOidcConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetPipelineOidcConfigResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bitbucket:index/getPipelineOidcConfig:getPipelineOidcConfig", {
        "workspace": args.workspace,
    }, opts);
}

/**
 * A collection of arguments for invoking getPipelineOidcConfig.
 */
export interface GetPipelineOidcConfigArgs {
    workspace: string;
}

/**
 * A collection of values returned by getPipelineOidcConfig.
 */
export interface GetPipelineOidcConfigResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly oidcConfig: string;
    readonly workspace: string;
}
export function getPipelineOidcConfigOutput(args: GetPipelineOidcConfigOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetPipelineOidcConfigResult> {
    return pulumi.output(args).apply((a: any) => getPipelineOidcConfig(a, opts))
}

/**
 * A collection of arguments for invoking getPipelineOidcConfig.
 */
export interface GetPipelineOidcConfigOutputArgs {
    workspace: pulumi.Input<string>;
}
