// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Provides a Bitbucket project branching model resource.
 *
 * This allows you for setting up branching models for your project.
 *
 * OAuth2 Scopes: `project:admin`
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as bitbucket from "@ryan-pip/pulumi_bitbucket";
 *
 * const exampleProject = new bitbucket.Project("exampleProject", {
 *     owner: "example",
 *     key: "FFFFF",
 * });
 * const exampleProjectBranchingModel = new bitbucket.ProjectBranchingModel("exampleProjectBranchingModel", {
 *     workspace: "example",
 *     project: exampleProject.key,
 *     development: {
 *         useMainbranch: true,
 *     },
 *     branchTypes: [
 *         {
 *             enabled: true,
 *             kind: "feature",
 *             prefix: "example/",
 *         },
 *         {
 *             enabled: true,
 *             kind: "hotfix",
 *             prefix: "hotfix/",
 *         },
 *         {
 *             enabled: true,
 *             kind: "release",
 *             prefix: "release/",
 *         },
 *         {
 *             enabled: true,
 *             kind: "bugfix",
 *             prefix: "bugfix/",
 *         },
 *     ],
 * });
 * ```
 *
 * ## Import
 *
 * Branching Models can be imported using the workspace and project separated by a (`/`), e.g.,
 *
 * ```sh
 *  $ pulumi import bitbucket:index/projectBranchingModel:ProjectBranchingModel example workspace/project
 * ```
 */
export class ProjectBranchingModel extends pulumi.CustomResource {
    /**
     * Get an existing ProjectBranchingModel resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProjectBranchingModelState, opts?: pulumi.CustomResourceOptions): ProjectBranchingModel {
        return new ProjectBranchingModel(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bitbucket:index/projectBranchingModel:ProjectBranchingModel';

    /**
     * Returns true if the given object is an instance of ProjectBranchingModel.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProjectBranchingModel {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProjectBranchingModel.__pulumiType;
    }

    /**
     * A set of branch type to define `feature`, `bugfix`, `release`, `hotfix` prefixes. See Branch Type below.
     */
    public readonly branchTypes!: pulumi.Output<outputs.ProjectBranchingModelBranchType[]>;
    /**
     * The development branch can be configured to a specific branch or to track the main branch. When set to a specific branch it must currently exist. Only the passed properties will be updated. The properties not passed will be left unchanged. A request without a development property will leave the development branch unchanged. See Development below.
     */
    public readonly development!: pulumi.Output<outputs.ProjectBranchingModelDevelopment>;
    /**
     * The production branch can be a specific branch, the main branch or disabled. When set to a specific branch it must currently exist. The enabled property can be used to enable (true) or disable (false) it. Only the passed properties will be updated. The properties not passed will be left unchanged. A request without a production property will leave the production branch unchanged. See Production below.
     */
    public readonly production!: pulumi.Output<outputs.ProjectBranchingModelProduction | undefined>;
    /**
     * The key of the project.
     */
    public readonly project!: pulumi.Output<string>;
    /**
     * The workspace of this project. Can be you or any team you
     * have write access to.
     */
    public readonly workspace!: pulumi.Output<string>;

    /**
     * Create a ProjectBranchingModel resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectBranchingModelArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProjectBranchingModelArgs | ProjectBranchingModelState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProjectBranchingModelState | undefined;
            resourceInputs["branchTypes"] = state ? state.branchTypes : undefined;
            resourceInputs["development"] = state ? state.development : undefined;
            resourceInputs["production"] = state ? state.production : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["workspace"] = state ? state.workspace : undefined;
        } else {
            const args = argsOrState as ProjectBranchingModelArgs | undefined;
            if ((!args || args.development === undefined) && !opts.urn) {
                throw new Error("Missing required property 'development'");
            }
            if ((!args || args.project === undefined) && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            if ((!args || args.workspace === undefined) && !opts.urn) {
                throw new Error("Missing required property 'workspace'");
            }
            resourceInputs["branchTypes"] = args ? args.branchTypes : undefined;
            resourceInputs["development"] = args ? args.development : undefined;
            resourceInputs["production"] = args ? args.production : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["workspace"] = args ? args.workspace : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProjectBranchingModel.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ProjectBranchingModel resources.
 */
export interface ProjectBranchingModelState {
    /**
     * A set of branch type to define `feature`, `bugfix`, `release`, `hotfix` prefixes. See Branch Type below.
     */
    branchTypes?: pulumi.Input<pulumi.Input<inputs.ProjectBranchingModelBranchType>[]>;
    /**
     * The development branch can be configured to a specific branch or to track the main branch. When set to a specific branch it must currently exist. Only the passed properties will be updated. The properties not passed will be left unchanged. A request without a development property will leave the development branch unchanged. See Development below.
     */
    development?: pulumi.Input<inputs.ProjectBranchingModelDevelopment>;
    /**
     * The production branch can be a specific branch, the main branch or disabled. When set to a specific branch it must currently exist. The enabled property can be used to enable (true) or disable (false) it. Only the passed properties will be updated. The properties not passed will be left unchanged. A request without a production property will leave the production branch unchanged. See Production below.
     */
    production?: pulumi.Input<inputs.ProjectBranchingModelProduction>;
    /**
     * The key of the project.
     */
    project?: pulumi.Input<string>;
    /**
     * The workspace of this project. Can be you or any team you
     * have write access to.
     */
    workspace?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a ProjectBranchingModel resource.
 */
export interface ProjectBranchingModelArgs {
    /**
     * A set of branch type to define `feature`, `bugfix`, `release`, `hotfix` prefixes. See Branch Type below.
     */
    branchTypes?: pulumi.Input<pulumi.Input<inputs.ProjectBranchingModelBranchType>[]>;
    /**
     * The development branch can be configured to a specific branch or to track the main branch. When set to a specific branch it must currently exist. Only the passed properties will be updated. The properties not passed will be left unchanged. A request without a development property will leave the development branch unchanged. See Development below.
     */
    development: pulumi.Input<inputs.ProjectBranchingModelDevelopment>;
    /**
     * The production branch can be a specific branch, the main branch or disabled. When set to a specific branch it must currently exist. The enabled property can be used to enable (true) or disable (false) it. Only the passed properties will be updated. The properties not passed will be left unchanged. A request without a production property will leave the production branch unchanged. See Production below.
     */
    production?: pulumi.Input<inputs.ProjectBranchingModelProduction>;
    /**
     * The key of the project.
     */
    project: pulumi.Input<string>;
    /**
     * The workspace of this project. Can be you or any team you
     * have write access to.
     */
    workspace: pulumi.Input<string>;
}
