// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RepositoryVariable extends pulumi.CustomResource {
    /**
     * Get an existing RepositoryVariable resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RepositoryVariableState, opts?: pulumi.CustomResourceOptions): RepositoryVariable {
        return new RepositoryVariable(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bitbucket:index/repositoryVariable:RepositoryVariable';

    /**
     * Returns true if the given object is an instance of RepositoryVariable.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RepositoryVariable {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RepositoryVariable.__pulumiType;
    }

    public readonly key!: pulumi.Output<string>;
    public readonly repository!: pulumi.Output<string>;
    public readonly secured!: pulumi.Output<boolean | undefined>;
    public /*out*/ readonly uuid!: pulumi.Output<string>;
    public readonly value!: pulumi.Output<string>;

    /**
     * Create a RepositoryVariable resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RepositoryVariableArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RepositoryVariableArgs | RepositoryVariableState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RepositoryVariableState | undefined;
            resourceInputs["key"] = state ? state.key : undefined;
            resourceInputs["repository"] = state ? state.repository : undefined;
            resourceInputs["secured"] = state ? state.secured : undefined;
            resourceInputs["uuid"] = state ? state.uuid : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
        } else {
            const args = argsOrState as RepositoryVariableArgs | undefined;
            if ((!args || args.key === undefined) && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if ((!args || args.repository === undefined) && !opts.urn) {
                throw new Error("Missing required property 'repository'");
            }
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["key"] = args ? args.key : undefined;
            resourceInputs["repository"] = args ? args.repository : undefined;
            resourceInputs["secured"] = args ? args.secured : undefined;
            resourceInputs["value"] = args?.value ? pulumi.secret(args.value) : undefined;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["value"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(RepositoryVariable.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RepositoryVariable resources.
 */
export interface RepositoryVariableState {
    key?: pulumi.Input<string>;
    repository?: pulumi.Input<string>;
    secured?: pulumi.Input<boolean>;
    uuid?: pulumi.Input<string>;
    value?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RepositoryVariable resource.
 */
export interface RepositoryVariableArgs {
    key: pulumi.Input<string>;
    repository: pulumi.Input<string>;
    secured?: pulumi.Input<boolean>;
    value: pulumi.Input<string>;
}
